---
sudo: required
language: python3
services: docker

before_install:
  - sudo apt-get install -y python3 python3-pip
addons:
  apt:
    update: true

env:
  - version=">=2.7,<2.8" distro="centos-latest"
  - version="" distro="centos-latest"

matrix:
  allow_failures:
    - env: version="devel" distro="centos-latest"

cache:
  - pip

install:
  - sudo python3.4 -m pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then sudo python3.4 -m pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then sudo python3.4 -m pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - sudo python3.4 -m pip install molecule
  - sudo python3.4 -m pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi
