---
- name: "{{ ansible_distribution }} - Install wget on Centos or RHEL"
  yum: name=wget state=present

- name: "{{ ansible_distribution }} - Install curl on Centos or RHEL"
  yum: name=curl state=present

- name: "{{ ansible_distribution }} - Install net-tools on Centos or RHEL"
  yum: name=net-tools state=present

- name: "{{ ansible_distribution }} - Install jq JSON parser on Centos or RHEL"
  yum: name=jq state=present
